### ISSUE TITLE
Specify your own volumes

### ISSUE THREAD

**Issue by JuicyLung91** [wordup-dev/wordup-cli#24]
Nice project!

How about specify your own volumes your want to mount. This would improve my git setup and my IDE workflow.

**Comment by shry** [comment]
You want to mount an existing docker volume of an already running WordPress container?

**Comment by JuicyLung91** [comment]
I would like to have the abillity to mount specific directories inside the wordpress container.
Let me explain this in two sections:

**First the git workflow:**
Right now if you develop a plugin the `src` directory is mounted with the `wp-content/plugins/plugin-name` directory or `wp-content/themes/theme-name` for theme development.But when you develop a plugin and a theme the whole `src` directory is mounted with the `wp-content` directory. Which ends up in a messy `src` directory. 

In the `src` directory there appear severel directories I don´t need in my git repo.

```
├── languages
    ├── most of the files I dont need in my git
├── plugin
    ├── my plugin i am developing
    ├── some other plugin I dont need in my git
    └── some other plugin I dont need in my git
├── theme
    ├── my theme am developing
    ├── some other theme I dont need in my git
    └── some other theme I dont need in my git
├── upgrade
├── uploads
    ├── maybe I need this but not for the initial local development
```

This ends up in a weird git ignore file. Where I have to exclude a whole directory and then write an exception for single directories. 

```
src/plugins/*
src/uploads
src/upgrade
src/languages
!src/plugins/rb-products
src/themes/*
!src/themes/theme
```

Maybe as an enhancment it would be a good solution to create your own mounts in the config file. Like this:
``` yaml
wpInstall:
  mounts: 
    - ./src/plugin-name/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
    - ./src/theme-name/:/var/www/html/wp-content/themes/theme-name# Theme development
```

**Second the IDE workflow:**
Right now my VSC doesn´t recognize the wordpress functions like `the_title()`. Because the wordpress data is not in my workspace. My IDE hilights the wordpress functions as errors.

I ended up to load the whole initial wordpress data into my root directory of the current workspace and then set this directory to gitignore. Now I don´t know if this is recommanded or if there is a better solution. 
But it would be a solution for me to mount the whole wordpress project inside a directory on the root level and the set this ignore this directory in the gitignore. 

``` yaml
wpInstall:
  mounts: 
     - ./wp-app:/var/www/html # Full wordpress project
```
