### ISSUE TITLE
Feature request: option to save db files in dir (not in volume)

### ISSUE THREAD

**Issue by simonmeggle** [wordup-dev/wordup-cli#28]
First, thanks for your valuable work. 
I want to ask for the feature to have also the database files on the host disk, not in a volume. 
The reason for this: I find it very convenient to "init/start" a wp project and then take the whole project directory under git version control. 
This enables me to save any state of the wp site with a commit and to revert/branch etc. (ok, merging database files would be by pain in the ass :-) )
From my understanding, the wizard only needs to ask "store db on volume (default=yes)", an if "no", the docker-compose file must be changed in one line: 

```
services:
  db:
    image: mariadb:10.3
    labels:
      - "wordup.dev"
    volumes:
      #- db_data:/var/lib/mysql
      - ./db_data:/var/lib/mysql
    restart: always
```
Regards,
Simon
